# Generated by Django 5.2 on 2025-04-26 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0002_trip_driver_alter_trip_current_cycle_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivinglog',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
