# Generated by Django 5.2 on 2025-04-26 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0003_drivinglog_date_drivinglog_remarks_trip_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivinglog',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='drivinglog',
            name='notes',
        ),
        migrations.AlterField(
            model_name='drivinglog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivinglog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
