# Generated by Django 5.0.2 on 2025-05-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0004_alter_drivinglog_options_remove_drivinglog_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='auto_assign',
            field=models.BooleanField(default=False),
        ),
    ]
