# Generated by Django 5.0.2 on 2025-05-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0005_trip_auto_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
